/**
 * mock.jsx のモックデータを React Native 型に合わせて変換
 */
import { Post, User, Comment, MyPost, TrendingPost, PastHotPost } from '../types';

export const MOCK_CURRENT_USER: User & { stats: { posts: number; helped: number; comments: number } } = {
  id: 'user_current',
  displayName: '田中太郎',
  avatar: '田',
  verified: true,
  bio: '伊集院町で八百屋をやっています。新鮮な野菜をお届け！',
  phone: '090-1234-5678',
  location: '伊集院町在住',
  stats: { posts: 12, helped: 5, comments: 28 },
};

const USERS: Record<string, User> = {
  user_001: { id: 'user_001', displayName: '田中商店', verified: true, avatar: '田', phone: '099-123-4567' },
  user_002: { id: 'user_002', displayName: '地域サバイバル部', verified: true, avatar: 'サ', phone: null },
  user_003: { id: 'user_003', displayName: '山田よしこ', verified: false, avatar: '山', phone: '090-1234-5678' },
  user_004: { id: 'user_004', displayName: '伊集院役所', verified: true, avatar: '役', phone: '099-248-1111' },
  user_005: { id: 'user_005', displayName: 'Bスーパー', verified: true, avatar: 'B', phone: '099-234-5678' },
  user_006: { id: 'user_006', displayName: '佐藤たけし', verified: false, avatar: '佐', phone: null },
};

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    category: 'stock',
    title: '卵入荷しました（残り少）',
    content: '本日朝入荷しました。地元養鶏場の新鮮卵です。お一人様2パックまで。',
    distance: 350,
    createdAt: '30分前',
    author: USERS.user_001,
    urgency: 'high',
    place: { name: '田中商店', address: '伊集院町徳重1丁目', latitude: 31.625, longitude: 130.387 },
    images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=300&fit=crop'],
    details: { price: '¥280/パック', stockStatus: '残りわずか', stockDuration: '48hours' },
    allowComments: true,
    isEnded: false,
    commentCount: 6,
    likeCount: 14,
  },
  {
    id: '2',
    category: 'event',
    title: '家庭菜園はじめよう講座',
    content: 'プランターでできる野菜づくりの基礎を学びます。初心者大歓迎！',
    distance: 600,
    createdAt: '2時間前',
    author: USERS.user_002,
    place: { name: '伊集院公民館', address: '伊集院町徳重', latitude: 31.62, longitude: 130.382 },
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop'],
    details: { eventDate: '3/9（日）', eventTime: '10:00〜', fee: '無料', maxParticipants: 15, currentParticipants: 8 },
    allowComments: true,
    isEnded: false,
    commentCount: 3,
    likeCount: 28,
  },
  {
    id: '3',
    category: 'help',
    title: '薪運びを手伝ってください',
    content: '裏山の薪を自宅まで運びたいです。お礼に野菜をお渡しします。',
    distance: 200,
    createdAt: '1時間前',
    author: USERS.user_003,
    urgency: 'medium',
    place: { name: '山田さん宅付近', address: '伊集院町下谷口', latitude: 31.618, longitude: 130.381 },
    images: [],
    details: { helpType: 'request', reward: '自家製野菜', estimatedTime: '30分〜1時間' },
    allowComments: true,
    isEnded: false,
    commentCount: 6,
    likeCount: 9,
  },
  {
    id: '4',
    category: 'admin',
    title: '燃料費高騰対策給付金',
    content: '対象世帯に5,000円を給付します。届いたハガキと本人確認書類をお持ちください。',
    distance: 800,
    createdAt: '今朝',
    author: USERS.user_004,
    urgency: 'high',
    place: { name: '日置市役所', address: '伊集院町郡1丁目', latitude: 31.623, longitude: 130.386 },
    images: [],
    details: { deadline: '3/15（金）17:00', requirements: ['届いたハガキ', '本人確認書類', '振込口座がわかるもの'] },
    allowComments: true,
    isEnded: false,
    commentCount: 2,
    likeCount: 5,
  },
  {
    id: '5',
    category: 'stock',
    title: '灯油 特価販売中',
    content: '18L 1,800円（通常1,980円）。配達も承ります。',
    distance: 1200,
    createdAt: '3時間前',
    author: USERS.user_005,
    place: { name: 'Bスーパー', address: '伊集院町猪鹿倉', latitude: 31.621, longitude: 130.389 },
    images: [],
    details: { price: '¥1,800/18L', stockStatus: '在庫あり' },
    allowComments: true,
    isEnded: false,
    commentCount: 1,
    likeCount: 3,
  },
  {
    id: '6',
    category: 'help',
    title: '【お裾分け】大根たくさん採れました',
    content: '大根が豊作で食べきれません。1人2本まで。',
    distance: 250,
    createdAt: '4時間前',
    author: USERS.user_006,
    place: { name: '佐藤さん宅', address: '伊集院町下谷口', latitude: 31.619, longitude: 130.382 },
    images: ['https://images.unsplash.com/photo-1447175008436-054170c2e979?w=400&h=300&fit=crop'],
    details: { helpType: 'share', reward: '大根（1人2本まで）' },
    allowComments: true,
    isEnded: false,
    commentCount: 4,
    likeCount: 21,
  },
  {
    id: '7',
    category: 'event',
    title: '防災訓練・避難経路確認',
    content: '参加者には非常食セットをプレゼント！',
    distance: 900,
    createdAt: '5時間前',
    author: USERS.user_002,
    place: { name: '妙円寺公園', address: '伊集院町徳重', latitude: 31.618, longitude: 130.38 },
    images: [],
    details: { eventDate: '3/10（月）', eventTime: '9:00〜', fee: '無料', maxParticipants: 50, currentParticipants: 23 },
    allowComments: true,
    isEnded: false,
    commentCount: 5,
    likeCount: 32,
  },
  {
    id: '8',
    category: 'stock',
    title: '春キャベツ・新玉ねぎ入荷',
    content: '地元農家さんの春野菜。キャベツ1玉150円。',
    distance: 450,
    createdAt: '6時間前',
    author: USERS.user_001,
    place: { name: 'JA直売所', address: '伊集院町徳重2丁目', latitude: 31.625, longitude: 130.387 },
    images: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop'],
    details: { price: '¥150〜', stockStatus: '在庫あり' },
    allowComments: true,
    isEnded: false,
    commentCount: 2,
    likeCount: 7,
  },
];

export const MOCK_COMMENTS: Comment[] = [
  { id: '1', author: USERS.user_006, content: '明日の午前なら手伝えます！軽トラも出せます。', createdAt: '10分前', canHelp: true },
  { id: '2', author: USERS.user_005, content: '軽トラ出せますよ 何時頃がいいですか？', createdAt: '25分前', canHelp: true },
  { id: '3', author: USERS.user_001, content: '何時頃がご希望ですか？うちの息子も手伝えるかも。', createdAt: '30分前', canHelp: false },
  { id: '4', author: USERS.user_002, content: '私も参加できます！道具は持っていきましょうか？', createdAt: '45分前', canHelp: true },
  { id: '5', author: USERS.user_004, content: '役所からも応援出せるかもしれません。確認します。', createdAt: '1時間前', canHelp: false },
  { id: '6', author: USERS.user_006, content: '友人も誘ってみます！', createdAt: '2時間前', canHelp: true },
];

export const MOCK_TRENDING: TrendingPost[] = [
  { id: 101, category: 'event', title: '餅つき大会', spotName: '妙円寺公園', distance: 400, time: '今日 14:00〜', comments: 23, likes: 45 },
  { id: 102, category: 'stock', title: '年末セール 全品20%OFF', spotName: 'Bスーパー', distance: 1200, time: '今日限り', comments: 12, likes: 38 },
  { id: 103, category: 'help', title: '雪かきボランティア募集', spotName: '伊集院駅前', distance: 300, time: '今日 8:00〜', comments: 31, likes: 67 },
];

export const MOCK_PAST_HOT: PastHotPost[] = [
  { id: 201, category: 'event', title: '夏祭り盆踊り大会', spotName: '妙円寺公園', time: '2024/8/15', comments: 89, likes: 234, participants: 150 },
  { id: 202, category: 'help', title: '台風19号 復旧ボランティア', spotName: '伊集院町全域', time: '2024/9/22', comments: 156, likes: 412, participants: 80 },
  { id: 203, category: 'event', title: '新春もちつき大会', spotName: '伊集院公民館', time: '2024/1/3', comments: 67, likes: 189, participants: 120 },
];

export const MOCK_MY_POSTS: MyPost[] = [
  { id: 101, category: 'stock', title: '卵入荷しました（残り少）', time: '30分前', status: 'active', views: 45, comments: 6 },
  { id: 102, category: 'help', title: '薪運びを手伝ってください', time: '2日前', status: 'active', views: 89, comments: 12 },
  { id: 103, category: 'event', title: '朝市のお知らせ', time: '1週間前', status: 'ended', views: 234, comments: 45 },
];
